name: CI/CD Pipeline for Model Serving

on:
  push:
    branches:
      - main # Trigger on pushes to the main branch
  pull_request:
    branches:
      - main # Trigger on pull requests to the main branch

jobs:
  build-and-push:
    runs-on: ubuntu-latest # Use an Ubuntu runner

    permissions:
      contents: read
      packages: write # Required to push to GitHub Container Registry

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }} # GITHUB_TOKEN is a built-in secret

    - name: Set Docker image name and tag
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ghcr.io/${{ github.repository }} # Your image name will be ghcr.io/your_github_username/your_repo_name
        tags: |
          type=raw,value=latest,enable=${{ github.ref == 'refs/heads/main' }} # Tag main branch builds as latest
          type=sha # Tag with short Git SHA

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: . # Build context is the root of your repository
        push: true # Push the image to the registry
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: type=gha # Use GitHub Actions cache for faster builds
        cache-to: type=gha,mode=max